### ISSUE TITLE
shapely deprecation warning during convert_polygons

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/schimpy#27]
* schimpy version: 1.4.2
* Python version: 3.9
* Operating System: Windows

### Description
(py39) F:\volume_chapter>convert_polygons --input LegalDelta_edited.shp --output delta.yaml
C:\Users\eli\Miniconda3\envs\py39\lib\site-packages\schimpy\schism_polygon.py:35: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0

**Comment by kjnam** [comment]
It is a known issue with Shapely ver 2. Please use Shapely 1.8 for now. We will adopt ver 2 soon.

**Comment by water-e** [comment]
@kjnam Do we have a "last version with Shapely 1.0" with 1.0 as the requirement yet? Which is expected in master right now?

**Comment by kjnam** [comment]
@water-e The branch to migrate to Shapely 2.0 is not merged yet, and the master is not tagged. So, you are right, the current HEAD of the master uses Shapely 1.

**Comment by kjnam** [comment]
I think this is resolved now as described in #33.
